# _config.yml for Jekyll site with custom configurations

# Theme settings
theme: jekyll-theme-minimal  # Use the minimal theme
@import "{{ site.theme }}";  # Import the theme's settings

# Site settings
title: Programas & Aplicaciones          # Site title
description: Configuraciones, Programas & Aplicaciones  # Site description

# Build settings
lsi: false             # Latent Semantic Indexing for related posts, set to false for faster builds
safe: true             # Safe mode, restricts custom plugins for GitHub Pages compatibility
source: .              # Source directory is the root
incremental: false     # Incremental build, set to false for full rebuilds
highlighter: rouge     # Syntax highlighter

# Gist settings
gist:
  noscript: false      # Allows Gists to work without JavaScript

# Markdown processing with Kramdown
kramdown:
  math_engine: mathjax       # Use MathJax for math rendering
  syntax_highlighter: rouge  # Syntax highlighting with Rouge

# Add additional custom configurations below
