remote_theme: ThomasBoxall/ghp-simple-dark
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""  # Aplica a todos los archivos
    values:
      layout: default
sass:
  quiet_deps: true
  sass_dir: assets/css
  style: compressed
